#!/usr/bin/env bash
#
# DESCRIPTION: standard test for Isabelle/Dedukti

set -e

OUTPUT="${1:-isabelle_dedukti_test}"

if [ -d $OUTPUT ]; then
    if [ ! -f "$OUTPUT/lambdapi.pkg" ]; then
        echo "$OUTPUT is not a lambdapi package directory"
        exit 1
    fi
else
    $ISABELLE_LAMBDAPI init "${OUTPUT//"/"/.}"
fi

isabelle dedukti_import -O "$OUTPUT/main.lp" Dedukti_Base

(cd "$OUTPUT" && sed -i -e 's/SRC = *$/SRC = main.lp/g' Makefile && make)
