#!/usr/bin/env bash
#
# DESCRIPTION: standard test for Isabelle/Dedukti

set -e

OUTPUT="${1:-output.lp}"

isabelle dedukti_import -O "$OUTPUT" Dedukti_Import

(cd "`dirname "$OUTPUT"`" && "$ISABELLE_LAMBDAPI" "`basename "$OUTPUT"`")
