#!/usr/bin/env bash
#
# DESCRIPTION: fresh build of jar for Isabelle/Dedukti

set -e


## sources

declare -a SOURCES=(
  src/importer.scala
  src/lambdapi.scala
  src/writers.scala
  src/translate.scala
  src/tools.scala
)


## main

isabelle jedit -b

# compile sources
cd "$ISABELLE_DEDUKTI_HOME"

TARGET_DIR="lib/classes"
rm -rf "$TARGET_DIR" && mkdir -p "$TARGET_DIR"

TARGET="dedukti.jar"
echo "Building $PWD/$TARGET_DIR/$TARGET ..."

SCALAC_OPTIONS="$ISABELLE_SCALAC_OPTIONS -d $TARGET_DIR"
export CLASSPATH="$(platform_path "$ISABELLE_CLASSPATH")"
isabelle_scala scalac $SCALAC_OPTIONS "${SOURCES[@]}"

# make jar
cd "$TARGET_DIR"
isabelle_jdk jar cf "$TARGET" isabelle/dedukti/*.class lambdapi/*.class

rm -rf isabelle lambdapi

# create gradle project (e.g. for IntelliJ IDEA)
GRADLE_PROJECT="$ISABELLE_DEDUKTI_HOME/gradle_project"
rm -rf "$GRADLE_PROJECT"
isabelle scala_project -L "$GRADLE_PROJECT"
mkdir -p "$GRADLE_PROJECT/src/main/scala/isabelle.dedukti"

for SRC in "${SOURCES[@]}"
do
  ln -s "$ISABELLE_DEDUKTI_HOME/src/$SRC" "$GRADLE_PROJECT/src/main/scala/isabelle.dedukti"
done
